version: '3.8'
services: 
  nginx:
    image: nginx:1.19.1-alpine
    ports: 
      - 80:80
    volumes: 
      - ./src:/var/www/php:ro
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - phpmyadmin-data:/usr/src/phpmyadmin
    depends_on: 
      - php
      - phpmyadmin
  php:
    build: ./.docker/php
    working_dir: /var/www/php
    volumes: 
      - ./src:/var/www/php
    depends_on: 
      - mysql
  mysql:
    image: mysql:latest
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: beo
      MYSQL_PASSWORD: Hai@1999
      MYSQL_DATABASE: QUALK
    volumes: 
      - ./.docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro
      - mysql-data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports: 
      - 8080:80
    environment: 
      PMA_HOST: mysql
    volumes: 
      - phpmyadmin-data:/usr/src/phpmyadmin
    depends_on: 
      - mysql
volumes: 
  mysql-data:
  phpmyadmin-data: